insert into public.converts (id, name, gender, age, ward, confirmation_date, months_membership) values
('batasan-hills-1st-1', 'Baluyot, Elias', 'M', 13, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-2', 'Carillo, Arius', 'M', 9, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-3', 'Cereño Lapido, Jai Lei', 'F', 9, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-4', 'Chin Andria Basilio', 'F', 8, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-5', 'Laurel, Rizalina Niagas', 'F', 66, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-6', 'Liguan, June Lexian Lorico', 'F', 10, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-7', 'Liguan, Lurk Vixen Lorico', 'F', 13, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-8', 'Malate, Hezekiah', 'M', 10, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-9', 'Malate, Ranel M.', 'M', 33, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-10', 'Metran, Franchesca', 'F', 12, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-11', 'Metran, Jerain', 'M', 20, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-12', 'Metran, Jermagne Sabugar', 'F', 19, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-13', 'Sabugar Metran, Flora', 'F', 39, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-14', 'Shaya Carillo', 'F', 8, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-15', 'Tagalog, Francel Nacionales', 'F', 20, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-16', 'Tagalog, Franchesca Marie Nacionales', 'F', 11, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-17', 'Tagalog, Franck Nacionales', 'M', 15, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-18', 'Tagalog, Franky Marie Nacionales', 'F', 23, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-19', 'Tagalog Jr., Francisco Sorita', 'M', 61, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-20', 'Toledo, Sophia Kim', 'F', 15, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-21', 'Yamson, Rhian Jane', 'F', 19, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-1st-22', 'Yanila, Jay-ar Relis', 'M', 25, 'Batasan Hills 1st', 'Not reported', null),
('batasan-hills-2nd-1', 'Aldaya, Leona Jane', 'F', 9, 'Batasan Hills 2nd', 'Not reported', null),
('batasan-hills-2nd-2', 'Antonio, Angilica Hofiliña Mendoza', 'F', 37, 'Batasan Hills 2nd', 'Not reported', null),
('batasan-hills-2nd-3', 'Autor, Jenna', 'F', 12, 'Batasan Hills 2nd', 'Not reported', null),
('batasan-hills-2nd-4', 'Basada, Conner Cañete', 'M', 11, 'Batasan Hills 2nd', 'Not reported', null),
('batasan-hills-2nd-5', 'Calbitaza, Andrei', 'M', 9, 'Batasan Hills 2nd', 'Not reported', null),
('batasan-hills-2nd-6', 'Clores, Prince Harry Iñigo', 'M', 10, 'Batasan Hills 2nd', 'Not reported', null),
('batasan-hills-2nd-7', 'Dela Cruz, John Philip Motita', 'M', 10, 'Batasan Hills 2nd', 'Not reported', null),
('batasan-hills-2nd-8', 'Flores, Marlon Jarabejo', 'M', 38, 'Batasan Hills 2nd', 'Not reported', null),
('batasan-hills-2nd-9', 'Huete, Merian Claire Deldacan', 'F', 18, 'Batasan Hills 2nd', 'Not reported', null),
('batasan-hills-2nd-10', 'Khan Jr., Michael Angelo Clores', 'M', 12, 'Batasan Hills 2nd', 'Not reported', null),
('batasan-hills-2nd-11', 'Mañozo, Lido Jr.', 'M', 27, 'Batasan Hills 2nd', 'Not reported', null),
('batasan-hills-2nd-12', 'Pascua Ramos, Ofelia', 'F', 76, 'Batasan Hills 2nd', 'Not reported', null),
('batasan-hills-2nd-13', 'Sunajo, Joey Pineda', 'M', 50, 'Batasan Hills 2nd', 'Not reported', null),
('bagong-silangan-1', 'Amor, Genalyn', 'F', 34, 'Bagong Silangan', 'Not reported', null),
('bagong-silangan-2', 'Aying, Vivian', 'F', 45, 'Bagong Silangan', 'Not reported', null),
('bagong-silangan-3', 'Briones, Ma. Janna Quilicol', 'F', 22, 'Bagong Silangan', 'Not reported', null),
('bagong-silangan-4', 'Cabador, Franzhys Justo', 'M', 17, 'Bagong Silangan', 'Not reported', null),
('bagong-silangan-5', 'Flores, Alexis Almirol', 'M', 18, 'Bagong Silangan', 'Not reported', null),
('bagong-silangan-6', 'Inoncillo, Terenel', 'M', 12, 'Bagong Silangan', 'Not reported', null),
('bagong-silangan-7', 'Martinez, Aixen Raile Bantiling', 'M', 9, 'Bagong Silangan', 'Not reported', null),
('bagong-silangan-8', 'Millapes, Princess Savannah', 'F', 9, 'Bagong Silangan', 'Not reported', null),
('bagong-silangan-9', 'Pardiñas, Quinn Via', 'F', 10, 'Bagong Silangan', 'Not reported', null),
('bagong-silangan-10', 'Ped, Arlyn', 'F', 14, 'Bagong Silangan', 'Not reported', null),
('bagong-silangan-11', 'Porras, April Joy', 'F', 33, 'Bagong Silangan', 'Not reported', null),
('bagong-silangan-12', 'Quares, Rodesh', 'M', 13, 'Bagong Silangan', 'Not reported', null),
('bagong-silangan-13', 'Sarahan, Erwin', 'M', 46, 'Bagong Silangan', 'Not reported', null),
('bagong-silangan-14', 'Torres, Jeremy', 'M', 23, 'Bagong Silangan', 'Not reported', null),
('don-antonio-1', 'Cabigayan, Demetrio Altaque', 'M', 86, 'Don Antonio', 'Not reported', null),
('don-antonio-2', 'Estrada, Bryan Anthony Ruiz', 'M', 32, 'Don Antonio', 'Not reported', null),
('don-antonio-3', 'Faina, Ram Calvin Ratuita', 'M', 12, 'Don Antonio', 'Not reported', null),
('don-antonio-4', 'Montes, Juanito Cabunilas', 'M', 65, 'Don Antonio', 'Not reported', null),
('don-antonio-5', 'Paligar, Kris Arjane Yuhan', 'M', 15, 'Don Antonio', 'Not reported', null),
('don-antonio-6', 'Perez, Amelia Cail Santos', 'F', 18, 'Don Antonio', 'Not reported', null),
('fairview-1', 'Agaid, Renato', 'M', 76, 'Fairview', 'Not reported', null),
('fairview-2', 'Agaid, Rosalinda Gapol', 'F', 55, 'Fairview', 'Not reported', null),
('fairview-3', 'Balanza, Louriese Agapan', 'F', 9, 'Fairview', 'Not reported', null),
('fairview-4', 'Bendanillo, Kristine Baring', 'F', 51, 'Fairview', 'Not reported', null),
('fairview-5', 'Buloran, Fiona Tanael', 'F', 15, 'Fairview', 'Not reported', null),
('fairview-6', 'Cabcaban, Mae Rose', 'F', 48, 'Fairview', 'Not reported', null),
('fairview-7', 'Espineda, Claire Jean Dicen', 'F', 13, 'Fairview', 'Not reported', null),
('fairview-8', 'Fuensalida, Connie', 'F', 39, 'Fairview', 'Not reported', null),
('fairview-9', 'Fuensalida, Darryl Gabe', 'M', 12, 'Fairview', 'Not reported', null),
('fairview-10', 'Goco, Christopher John Guerero', 'M', 46, 'Fairview', 'Not reported', null),
('fairview-11', 'Hermoso, Angel Mae Calledo', 'F', 16, 'Fairview', 'Not reported', null),
('fairview-12', 'Ignas, Rafael Beboso', 'M', 75, 'Fairview', 'Not reported', null),
('fairview-13', 'Jereza, Prince Josh Pestaño', 'M', 10, 'Fairview', 'Not reported', null),
('fairview-14', 'Joban, Merlinda Fresnido', 'F', 58, 'Fairview', 'Not reported', null),
('fairview-15', 'Maglente, Angela Modar', 'F', 11, 'Fairview', 'Not reported', null),
('fairview-16', 'Mercado, Erlin Engo', 'F', 63, 'Fairview', 'Not reported', null),
('fairview-17', 'Navarez, Zeus', 'M', 9, 'Fairview', 'Not reported', null),
('fairview-18', 'Padua, Julie Nisperos', 'F', 38, 'Fairview', 'Not reported', null),
('fairview-19', 'Paloma, Angela', 'F', 13, 'Fairview', 'Not reported', null),
('fairview-20', 'Paloma, Jamaica Lampas', 'F', 17, 'Fairview', 'Not reported', null),
('fairview-21', 'Pestaño, Calvin Baguinbuin', 'M', 10, 'Fairview', 'Not reported', null),
('fairview-22', 'Pestaño, Hanna Eunice', 'F', 13, 'Fairview', 'Not reported', null),
('fairview-23', 'Pontillo, Ma. Allysa Mae Gabuya', 'F', 15, 'Fairview', 'Not reported', null),
('fairview-24', 'Pontillo, Ma. Althea Mae Gabuya', 'F', 13, 'Fairview', 'Not reported', null),
('fairview-25', 'Racan, Jefferson Saturñino', 'M', 29, 'Fairview', 'Not reported', null),
('fairview-26', 'Rocero, Ma. Chona Gadlan', 'F', 54, 'Fairview', 'Not reported', null),
('fairview-27', 'Salas, Ma. Jocelyn Pamanian', 'F', 17, 'Fairview', 'Not reported', null),
('fairview-28', 'Samar, Eduardo Beriña', 'M', 66, 'Fairview', 'Not reported', null),
('fairview-29', 'Santos, Joshua Alquiza', 'M', 10, 'Fairview', 'Not reported', null),
('fairview-30', 'Taconing, Melka', 'F', 19, 'Fairview', 'Not reported', null),
('fairview-31', 'Tapia, Jeric Amodia', 'M', 21, 'Fairview', 'Not reported', null),
('kalayaan-1', 'Abilar, Brent Cedric Adapon', 'M', 17, 'Kalayaan', 'Not reported', null),
('kalayaan-2', 'Baro, Lhyra Cerbito', 'F', 11, 'Kalayaan', 'Not reported', null),
('kalayaan-3', 'Calicdan, Kiesha Janella Ruado', 'F', 8, 'Kalayaan', 'Not reported', null),
('kalayaan-4', 'Ere, Lea Maine', 'F', 10, 'Kalayaan', 'Not reported', null),
('kalayaan-5', 'Erie, Kurtnel Hermosura', 'M', 8, 'Kalayaan', 'Not reported', null),
('kalayaan-6', 'Gerundio, Hermogenes Cano Sr', 'M', 65, 'Kalayaan', 'Not reported', null),
('kalayaan-7', 'Matuguinas, Yolly', 'F', 41, 'Kalayaan', 'Not reported', null),
('kalayaan-8', 'Quetua, Judith Usero', 'F', 66, 'Kalayaan', 'Not reported', null),
('kalayaan-9', 'Revilla, Dinah Rose Quinikito', 'F', 11, 'Kalayaan', 'Not reported', null),
('kalayaan-10', 'Rivera, Stephen Roy', 'M', 15, 'Kalayaan', 'Not reported', null),
('kalayaan-11', 'Sureta, Jerolyn Vibal', 'F', 9, 'Kalayaan', 'Not reported', null),
('kalayaan-12', 'Trinidad, Clyde', 'M', 10, 'Kalayaan', 'Not reported', null),
('kalayaan-13', 'Trinidad, Czarina Alessandra', 'F', 16, 'Kalayaan', 'Not reported', null),
('mapayapa-1', 'Abayon, Thea', 'F', 15, 'Mapayapa', 'Not reported', null),
('mapayapa-2', 'Altiche, Reinna Medina', 'F', 9, 'Mapayapa', 'Not reported', null),
('mapayapa-3', 'Cruzata, DJ Arci', 'F', 14, 'Mapayapa', 'Not reported', null),
('mapayapa-4', 'Demetillo, Edmar Bañaco', 'M', 43, 'Mapayapa', 'Not reported', null),
('mapayapa-5', 'Fernandez, Ronielyn Nerbato', 'F', 21, 'Mapayapa', 'Not reported', null),
('mapayapa-6', 'Forio, Jezil Castillo', 'F', 23, 'Mapayapa', 'Not reported', null),
('mapayapa-7', 'Mengote, Arkyn Zion Baleña', 'M', 10, 'Mapayapa', 'Not reported', null),
('mapayapa-8', 'Merced, John Christianeil Madriaga', 'M', 20, 'Mapayapa', 'Not reported', null),
('mapayapa-9', 'Merced, Precious Waesha', 'F', 15, 'Mapayapa', 'Not reported', null),
('mapayapa-10', 'Morales, Jhenalyn Mhae', 'F', 11, 'Mapayapa', 'Not reported', null),
('mapayapa-11', 'Navarro, Fairy Jane Cuartela', 'F', 10, 'Mapayapa', 'Not reported', null),
('mapayapa-12', 'Nerbato, Prince RJ', 'M', 9, 'Mapayapa', 'Not reported', null),
('mapayapa-13', 'Ong, Letticia Reyes', 'F', 64, 'Mapayapa', 'Not reported', null),
('mapayapa-14', 'Ruelo, Callie Brielle Wenceslao', 'F', 13, 'Mapayapa', 'Not reported', null),
('mapayapa-15', 'Ruelo, Keith Gabrielle Wenceslao', 'M', 12, 'Mapayapa', 'Not reported', null)
on conflict (id) do nothing;
