import { ArrowUpDown, Download, Eye, MoreHorizontal } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { RecentReportRow, ReportStatus } from '../../types/reports'

interface RecentReportsTableProps {
  rows: RecentReportRow[]
}

type SortKey = 'name' | 'type' | 'generatedBy' | 'date' | 'status' | 'fileSize'
type SortDirection = 'asc' | 'desc'

const statusStyles: Record<ReportStatus, string> = {
  Ready: 'border-emerald-400/30 bg-emerald-500/10 text-emerald-300',
  Generating: 'border-sky-400/30 bg-sky-500/10 text-sky-300',
  Scheduled: 'border-violet-400/30 bg-violet-500/10 text-violet-300',
  Failed: 'border-rose-400/30 bg-rose-500/10 text-rose-300',
  Shared: 'border-amber-400/30 bg-amber-500/10 text-amber-300',
}

export default function RecentReportsTable({ rows }: RecentReportsTableProps) {
  const [query, setQuery] = useState('')
  const [statusFilter, setStatusFilter] = useState('All')
  const [sortKey, setSortKey] = useState<SortKey>('date')
  const [sortDirection, setSortDirection] = useState<SortDirection>('desc')
  const [currentPage, setCurrentPage] = useState(1)
  const pageSize = 5

  const filteredRows = useMemo(() => {
    const normalized = query.trim().toLowerCase()

    return rows.filter((row) => {
      const matchesQuery =
        normalized.length === 0 ||
        row.name.toLowerCase().includes(normalized) ||
        row.generatedBy.toLowerCase().includes(normalized) ||
        row.type.toLowerCase().includes(normalized)

      const matchesStatus = statusFilter === 'All' || row.status === statusFilter

      return matchesQuery && matchesStatus
    })
  }, [query, rows, statusFilter])

  const sortedRows = useMemo(() => {
    const items = [...filteredRows]

    items.sort((a, b) => {
      const direction = sortDirection === 'asc' ? 1 : -1

      if (sortKey === 'date') {
        return (new Date(a.date).getTime() - new Date(b.date).getTime()) * direction
      }

      if (sortKey === 'status') {
        return a.status.localeCompare(b.status) * direction
      }

      if (sortKey === 'fileSize') {
        const left = parseFloat(a.fileSize)
        const right = parseFloat(b.fileSize)
        return (left - right) * direction
      }

      return String(a[sortKey]).localeCompare(String(b[sortKey])) * direction
    })

    return items
  }, [filteredRows, sortDirection, sortKey])

  const totalPages = Math.max(1, Math.ceil(sortedRows.length / pageSize))
  const pagedRows = sortedRows.slice((currentPage - 1) * pageSize, currentPage * pageSize)

  const handleSort = (key: SortKey) => {
    if (sortKey === key) {
      setSortDirection((current) => (current === 'asc' ? 'desc' : 'asc'))
      return
    }

    setSortKey(key)
    setSortDirection('desc')
  }

  return (
    <div className="overflow-hidden rounded-[30px] border border-white/10 bg-slate-950/60 shadow-[0_30px_80px_rgba(15,23,42,0.24)] backdrop-blur-xl">
      <div className="flex flex-col gap-4 border-b border-white/10 px-5 py-4 sm:px-6 xl:flex-row xl:items-center xl:justify-between">
        <div>
          <p className="text-[0.7rem] uppercase tracking-[0.28em] text-slate-400">Reports</p>
          <h3 className="mt-2 text-2xl font-semibold text-white">Recent reports</h3>
        </div>

        <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
          <input
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Search reports"
            className="w-full rounded-xl border border-white/10 bg-slate-900/80 px-3 py-2.5 text-sm text-slate-100 outline-none transition focus:border-sky-400/50 sm:w-56"
          />

          <select
            value={statusFilter}
            onChange={(event) => setStatusFilter(event.target.value)}
            className="rounded-xl border border-white/10 bg-slate-900/80 px-3 py-2.5 text-sm text-slate-100 outline-none transition focus:border-sky-400/50"
          >
            {['All', 'Ready', 'Generating', 'Scheduled', 'Shared', 'Failed'].map((option) => (
              <option key={option} value={option}>{option}</option>
            ))}
          </select>
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="min-w-full border-separate border-spacing-0 text-left">
          <thead>
            <tr className="bg-white/5 text-slate-300">
              {[
                ['Report Name', 'name'],
                ['Type', 'type'],
                ['Generated By', 'generatedBy'],
                ['Date', 'date'],
                ['Status', 'status'],
                ['File Size', 'fileSize'],
                ['Actions', 'actions'],
              ].map(([label, key]) => (
                <th key={label} className="px-5 py-3 text-xs uppercase tracking-[0.2em] text-slate-400 sm:px-6">
                  {key === 'actions' ? (
                    <span>{label}</span>
                  ) : (
                    <button type="button" onClick={() => handleSort(key as SortKey)} className="inline-flex items-center gap-2 transition hover:text-white">
                      {label}
                      <ArrowUpDown className="h-3 w-3 opacity-70" />
                    </button>
                  )}
                </th>
              ))}
            </tr>
          </thead>

          <tbody>
            {pagedRows.map((row) => (
              <tr key={row.id} className="border-t border-white/10 transition-colors hover:bg-white/[0.03]">
                <td className="px-5 py-4 text-sm font-medium text-white sm:px-6">{row.name}</td>
                <td className="px-5 py-4 text-sm text-slate-200 sm:px-6">{row.type}</td>
                <td className="px-5 py-4 text-sm text-slate-200 sm:px-6">{row.generatedBy}</td>
                <td className="px-5 py-4 text-sm text-slate-200 sm:px-6">{new Date(row.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</td>
                <td className="px-5 py-4 sm:px-6">
                  <span className={`inline-flex rounded-full border px-2.5 py-1 text-[0.7rem] font-medium ${statusStyles[row.status]}`}>
                    {row.status}
                  </span>
                </td>
                <td className="px-5 py-4 text-sm text-slate-200 sm:px-6">{row.fileSize}</td>
                <td className="px-5 py-4 sm:px-6">
                  <div className="flex items-center gap-2 text-slate-300">
                    <button type="button" aria-label={`View ${row.name}`} className="rounded-lg border border-white/10 bg-white/5 p-2 transition hover:border-white/15 hover:text-white">
                      <Eye className="h-3.5 w-3.5" />
                    </button>
                    <button type="button" aria-label={`Download ${row.name}`} className="rounded-lg border border-white/10 bg-white/5 p-2 transition hover:border-white/15 hover:text-white">
                      <Download className="h-3.5 w-3.5" />
                    </button>
                    <button type="button" aria-label={`More actions for ${row.name}`} className="rounded-lg border border-white/10 bg-white/5 p-2 transition hover:border-white/15 hover:text-white">
                      <MoreHorizontal className="h-3.5 w-3.5" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="flex flex-col gap-3 border-t border-white/10 px-5 py-4 text-sm text-slate-300 sm:flex-row sm:items-center sm:justify-between sm:px-6">
        <p>
          Showing {sortedRows.length === 0 ? 0 : (currentPage - 1) * pageSize + 1}-{Math.min(currentPage * pageSize, sortedRows.length)} of {sortedRows.length}
        </p>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => setCurrentPage((page) => Math.max(1, page - 1))}
            disabled={currentPage === 1}
            className="rounded-lg border border-white/10 bg-white/5 px-3 py-1.5 text-sm text-slate-200 disabled:cursor-not-allowed disabled:opacity-40"
          >
            Prev
          </button>
          <button
            type="button"
            onClick={() => setCurrentPage((page) => Math.min(totalPages, page + 1))}
            disabled={currentPage === totalPages}
            className="rounded-lg border border-white/10 bg-white/5 px-3 py-1.5 text-sm text-slate-200 disabled:cursor-not-allowed disabled:opacity-40"
          >
            Next
          </button>
        </div>
      </div>
    </div>
  )
}
